[package]
name = "rust_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
tokio = { version = "1.44.1", features = ["full"] }
tokio-tungstenite = "0.26.2"
warp = "0.3.7"
